# Configuration file for Zola
# https://www.getzola.org/documentation/getting-started/configuration/

# The base URL of the site; the only required configuration variable.
base_url = "https://oak.md"

# The site title and description; used in feeds by default.
title = "oak.md"
description = "请输入文本"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "hook"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
links = [
    { title = "About", href = "about" },
    { title = "Email", href = "mailto:tyg8614@gmail.com" },
    { title = "GitHub", href = "https://github.com/oak443" },
    { title = "Links", href = "links" },
    { title = "Luogu", href = "https://www.luogu.com.cn/user/1099057" },
    # ...
]
